changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: Technical debt
      labels:
        - ci
        - refactor
        - chore
        - test
    - title: Breaking changes
      labels:
        - breaking-change
    - title: New features
      labels:
        - feat
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Documentation
      labels:
        - docs
    - title: Other Changes
      labels:
        - "*"
