version: "3.9"
services:
  cosmos-db:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator@sha256:591621968db553b27872e74fcd1730755c5ced00cfe3b4ba180649bd8f43eeb3
    mem_limit: 3G
    cpu_count: 2
    tty: true
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=3
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    ports:
      - 8081:8081
      - 10251:10251
      - 10252:10252
      - 10253:10253
      - 10254:10254
    volumes:
      - cosmos-db-volume:/data/db
      
  storage:
    image: mcr.microsoft.com/azure-storage/azurite@sha256:647c63a91102a9d8e8000aab803436e1fc85fbb285e7ce830a82ee5d6661cf37
    command: "azurite -l /data --blobHost 0.0.0.0 --queueHost 0.0.0.0 --skipApiVersionCheck"
    ports:
      - 10000:10000
      - 10001:10001

volumes:
  cosmos-db-volume:
