version: "3.9"
services:
  cosmos-db:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator@sha256:244e4d3a93fb68b935b2d0924e211351b1dc907123a01f0d14c91cc85fa880ee
    mem_limit: 3G
    cpu_count: 2
    tty: true
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=3
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    ports:
      - 8081:8081
      - 10251:10251
      - 10252:10252
      - 10253:10253
      - 10254:10254
    volumes:
      - cosmos-db-volume:/data/db
      
  storage:
    image: mcr.microsoft.com/azure-storage/azurite@sha256:47a392f1c93a6b639999fc505dcae348e350183b47f2a7526c765ddd7fa56e0e
    command: "azurite -l /data --blobHost 0.0.0.0 --queueHost 0.0.0.0 --skipApiVersionCheck"
    ports:
      - 10000:10000
      - 10001:10001

volumes:
  cosmos-db-volume:
