packages:
  - packages/*
  - apps/*

configDependencies:
  pnpm-plugin-pagopa: 1.0.0+sha512-fWP4sdK5yH3OXi1oZeMEcMzBtjINfXx6woFOuzWtdlvuF7Co3vFJ3UIFLrOAolbYrXi4b3r2pIMESJt7vilizA==

catalog:
  '@azure/cosmos': ^4.0.0
  '@azure/functions': ^4.11.1
  '@azure/event-hubs': ^5.9.0
  '@azure/storage-blob': ^12.12.0
  '@azure/storage-queue': ^12.11.0
  '@pagopa/eslint-config': ^4.0.5
  '@pagopa/handler-kit': ^1.1.1
  '@pagopa/handler-kit-azure-func': ^2.0.8
  '@pagopa/io-functions-commons': ^29.0.0
  '@pagopa/io-functions-services-sdk': ^3.40.1
  '@pagopa/logger': ^1.0.1
  '@pagopa/openapi-codegen-ts': ^14.0.0
  '@pagopa/ts-commons': ^13.0.0
  '@types/node': ^20.17.6
  '@vitest/coverage-c8': ^0.33.0
  applicationinsights: ^2.9.5
  azure-functions-core-tools: ^4.0.5455
  date-fns: ^2.29.3
  eslint: ^8.57.0
  eslint-plugin-prettier: ^5.0.0
  fp-ts: ^2.16.5
  googleapis: ^133.0.0
  handler-kit-legacy: npm:@pagopa/handler-kit@0.5.1
  io-ts: ^2.2.21
  io-ts-types: ^0.5.19
  monocle-ts: ^2.3.13
  newtype-ts: ^0.3.5
  npm-pack-zip: ^1.3.0
  pdf-lib: ^1.17.1
  prettier: ^3.0.0
  rimraf: ^5.0.1
  tsup: ^7.2.0
  typescript: 5.3.3
  ulid: ^2.3.0
  undici: ^5.27.2
  vitest: ^1.2.2
  zod: ^3.22.4
