/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { enumType } from "@pagopa/ts-commons/lib/types";
import * as t from "io-ts";

export enum AssertionTypeEnum {
  "SAML" = "SAML",

  "OIDC" = "OIDC"
}

export type AssertionType = t.TypeOf<typeof AssertionType>;
export const AssertionType = enumType<AssertionTypeEnum>(
  AssertionTypeEnum,
  "AssertionType"
);
