/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { enumType } from "@pagopa/ts-commons/lib/types";

export enum TypeEnum {
  "REQUIRED" = "REQUIRED",

  "UNFAIR" = "UNFAIR",

  "OPTIONAL" = "OPTIONAL"
}

// required attributes
const ClauseR = t.interface({
  title: t.string,

  type: enumType<TypeEnum>(TypeEnum, "type")
});

// optional attributes
const ClauseO = t.partial({});

export const Clause = t.exact(t.intersection([ClauseR, ClauseO], "Clause"));

export type Clause = t.TypeOf<typeof Clause>;
