/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { Id } from "./Id";
import { Email } from "./Email";
import { DocumentToSign } from "./DocumentToSign";
import { QtspClauses } from "./QtspClauses";
import * as t from "io-ts";

// required attributes
const CreateSignatureBodyR = t.interface({
  signature_request_id: Id,

  email: Email,

  documents_to_sign: t.readonlyArray(DocumentToSign, "array of DocumentToSign"),

  qtsp_clauses: QtspClauses
});

// optional attributes
const CreateSignatureBodyO = t.partial({});

export const CreateSignatureBody = t.exact(
  t.intersection(
    [CreateSignatureBodyR, CreateSignatureBodyO],
    "CreateSignatureBody"
  )
);

export type CreateSignatureBody = t.TypeOf<typeof CreateSignatureBody>;
