/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { Id } from "./Id";
import { DocumentMetadata } from "./DocumentMetadata";
import { Timestamp } from "./Timestamp";
import * as t from "io-ts";

// required attributes
const DocumentDetailViewR = t.interface({
  id: Id,

  metadata: DocumentMetadata,

  url: t.string,

  created_at: Timestamp,

  updated_at: Timestamp
});

// optional attributes
const DocumentDetailViewO = t.partial({});

export const DocumentDetailView = t.exact(
  t.intersection(
    [DocumentDetailViewR, DocumentDetailViewO],
    "DocumentDetailView"
  )
);

export type DocumentDetailView = t.TypeOf<typeof DocumentDetailView>;
