/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { SignatureField } from "./SignatureField";
import * as t from "io-ts";

// required attributes
const DocumentMetadataR = t.interface({
  title: t.string,

  signature_fields: t.readonlyArray(SignatureField, "array of SignatureField")
});

// optional attributes
const DocumentMetadataO = t.partial({});

export const DocumentMetadata = t.exact(
  t.intersection([DocumentMetadataR, DocumentMetadataO], "DocumentMetadata")
);

export type DocumentMetadata = t.TypeOf<typeof DocumentMetadata>;
