/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { EmailString } from "@pagopa/ts-commons/lib/strings";
import * as t from "io-ts";

/**
 * User's email.
 */

export type Email = t.TypeOf<typeof Email>;
export const Email = EmailString;
