/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const FilledDocumentDetailViewR = t.interface({
  filled_document_url: t.string
});

// optional attributes
const FilledDocumentDetailViewO = t.partial({});

export const FilledDocumentDetailView = t.exact(
  t.intersection(
    [FilledDocumentDetailViewR, FilledDocumentDetailViewO],
    "FilledDocumentDetailView"
  )
);

export type FilledDocumentDetailView = t.TypeOf<
  typeof FilledDocumentDetailView
>;
