/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { FiscalCode as FiscalCodeT } from "@pagopa/ts-commons/lib/strings";
import * as t from "io-ts";

/**
 * User's fiscal code.
 */

export type FiscalCode = t.TypeOf<typeof FiscalCode>;
export const FiscalCode = FiscalCodeT;
