/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { FiscalCode } from "./FiscalCode";
import * as t from "io-ts";

// required attributes
const GetSignerByFiscalCodeBodyR = t.interface({
  fiscal_code: FiscalCode
});

// optional attributes
const GetSignerByFiscalCodeBodyO = t.partial({});

export const GetSignerByFiscalCodeBody = t.exact(
  t.intersection(
    [GetSignerByFiscalCodeBodyR, GetSignerByFiscalCodeBodyO],
    "GetSignerByFiscalCodeBody"
  )
);

export type GetSignerByFiscalCodeBody = t.TypeOf<
  typeof GetSignerByFiscalCodeBody
>;
