/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { enumType } from "@pagopa/ts-commons/lib/types";
import * as t from "io-ts";

export enum IssuerEnvironmentEnum {
  "TEST" = "TEST",

  "DEFAULT" = "DEFAULT"
}

export type IssuerEnvironment = t.TypeOf<typeof IssuerEnvironment>;
export const IssuerEnvironment = enumType<IssuerEnvironmentEnum>(
  IssuerEnvironmentEnum,
  "IssuerEnvironment"
);
