/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { enumType } from "@pagopa/ts-commons/lib/types";
import * as t from "io-ts";

export enum LollipopContentTypeEnum {
  "application/json" = "application/json",

  "application/octet-stream" = "application/octet-stream"
}

export type LollipopContentType = t.TypeOf<typeof LollipopContentType>;
export const LollipopContentType = enumType<LollipopContentTypeEnum>(
  LollipopContentTypeEnum,
  "LollipopContentType"
);
