/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { PatternString } from "@pagopa/ts-commons/lib/strings";
import * as t from "io-ts";

export type LollipopOriginalURL = t.TypeOf<typeof LollipopOriginalURL>;
export const LollipopOriginalURL = PatternString("^https://");
