/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { QtspClause } from "./QtspClause";
import * as t from "io-ts";
import { NonEmptyString } from "@pagopa/ts-commons/lib/strings";

// required attributes
const QtspClausesMetadataDetailViewR = t.interface({
  clauses: t.readonlyArray(QtspClause, "array of QtspClause"),

  document_url: t.string,

  privacy_url: t.string,

  privacy_text: NonEmptyString,

  terms_and_conditions_url: t.string,

  nonce: NonEmptyString
});

// optional attributes
const QtspClausesMetadataDetailViewO = t.partial({});

export const QtspClausesMetadataDetailView = t.exact(
  t.intersection(
    [QtspClausesMetadataDetailViewR, QtspClausesMetadataDetailViewO],
    "QtspClausesMetadataDetailView"
  )
);

export type QtspClausesMetadataDetailView = t.TypeOf<
  typeof QtspClausesMetadataDetailView
>;
