/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { NonEmptyString } from "@pagopa/ts-commons/lib/strings";

// required attributes
const QtspClauseR = t.interface({
  text: NonEmptyString
});

// optional attributes
const QtspClauseO = t.partial({});

export const QtspClause = t.exact(
  t.intersection([QtspClauseR, QtspClauseO], "QtspClause")
);

export type QtspClause = t.TypeOf<typeof QtspClause>;
