/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { SignatureRequestListView } from "./SignatureRequestListView";
import * as t from "io-ts";

// required attributes
const SignatureRequestListR = t.interface({
  items: t.readonlyArray(
    SignatureRequestListView,
    "array of SignatureRequestListView"
  )
});

// optional attributes
const SignatureRequestListO = t.partial({});

export const SignatureRequestList = t.exact(
  t.intersection(
    [SignatureRequestListR, SignatureRequestListO],
    "SignatureRequestList"
  )
);

export type SignatureRequestList = t.TypeOf<typeof SignatureRequestList>;
