/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { Id } from "./Id";
import { Timestamp } from "./Timestamp";
import * as t from "io-ts";
import { enumType } from "@pagopa/ts-commons/lib/types";

export enum StatusEnum {
  "CREATED" = "CREATED",

  "READY" = "READY",

  "WAITING" = "WAITING",

  "COMPLETED" = "COMPLETED",

  "FAILED" = "FAILED"
}

// required attributes
const SignatureDetailViewR = t.interface({
  id: Id,

  signature_request_id: Id,

  qtsp_signature_request_id: Id,

  status: enumType<StatusEnum>(StatusEnum, "status")
});

// optional attributes
const SignatureDetailViewO = t.partial({
  created_at: Timestamp,

  updated_at: Timestamp
});

export const SignatureDetailView = t.exact(
  t.intersection(
    [SignatureDetailViewR, SignatureDetailViewO],
    "SignatureDetailView"
  )
);

export type SignatureDetailView = t.TypeOf<typeof SignatureDetailView>;
