/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { Id } from "./Id";
import { DossierTitle } from "./DossierTitle";
import { SignatureRequestStatus } from "./SignatureRequestStatus";
import { Timestamp } from "./Timestamp";
import * as t from "io-ts";

// required attributes
const SignatureRequestListViewR = t.interface({
  id: Id,

  signer_id: Id,

  dossier_id: Id,

  dossier_title: DossierTitle,

  status: SignatureRequestStatus,

  created_at: Timestamp,

  updated_at: Timestamp,

  expires_at: Timestamp
});

// optional attributes
const SignatureRequestListViewO = t.partial({});

export const SignatureRequestListView = t.exact(
  t.intersection(
    [SignatureRequestListViewR, SignatureRequestListViewO],
    "SignatureRequestListView"
  )
);

export type SignatureRequestListView = t.TypeOf<
  typeof SignatureRequestListView
>;
