/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { NonNegativeNumber } from "@pagopa/ts-commons/lib/numbers";

// required attributes
const SignatureFieldToBeCreatedAttrsBottom_leftR = t.interface({
  x: t.number,

  y: t.number
});

// optional attributes
const SignatureFieldToBeCreatedAttrsBottom_leftO = t.partial({});

export const SignatureFieldToBeCreatedAttrsBottom_left = t.exact(
  t.intersection(
    [
      SignatureFieldToBeCreatedAttrsBottom_leftR,
      SignatureFieldToBeCreatedAttrsBottom_leftO
    ],
    "SignatureFieldToBeCreatedAttrsBottom_left"
  )
);

export type SignatureFieldToBeCreatedAttrsBottom_left = t.TypeOf<
  typeof SignatureFieldToBeCreatedAttrsBottom_left
>;

// required attributes
const SignatureFieldToBeCreatedAttrsTop_rightR = t.interface({
  x: t.number,

  y: t.number
});

// optional attributes
const SignatureFieldToBeCreatedAttrsTop_rightO = t.partial({});

export const SignatureFieldToBeCreatedAttrsTop_right = t.exact(
  t.intersection(
    [
      SignatureFieldToBeCreatedAttrsTop_rightR,
      SignatureFieldToBeCreatedAttrsTop_rightO
    ],
    "SignatureFieldToBeCreatedAttrsTop_right"
  )
);

export type SignatureFieldToBeCreatedAttrsTop_right = t.TypeOf<
  typeof SignatureFieldToBeCreatedAttrsTop_right
>;

// required attributes
const SignatureFieldToBeCreatedAttrsR = t.interface({
  bottom_left: SignatureFieldToBeCreatedAttrsBottom_left,

  top_right: SignatureFieldToBeCreatedAttrsTop_right,

  page: NonNegativeNumber
});

// optional attributes
const SignatureFieldToBeCreatedAttrsO = t.partial({});

export const SignatureFieldToBeCreatedAttrs = t.exact(
  t.intersection(
    [SignatureFieldToBeCreatedAttrsR, SignatureFieldToBeCreatedAttrsO],
    "SignatureFieldToBeCreatedAttrs"
  )
);

export type SignatureFieldToBeCreatedAttrs = t.TypeOf<
  typeof SignatureFieldToBeCreatedAttrs
>;
