/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { enumType } from "@pagopa/ts-commons/lib/types";
import * as t from "io-ts";

export enum SignatureRequestStatusEnum {
  "WAIT_FOR_SIGNATURE" = "WAIT_FOR_SIGNATURE",

  "WAIT_FOR_QTSP" = "WAIT_FOR_QTSP",

  "SIGNED" = "SIGNED",

  "REJECTED" = "REJECTED"
}

export type SignatureRequestStatus = t.TypeOf<typeof SignatureRequestStatus>;
export const SignatureRequestStatus = enumType<SignatureRequestStatusEnum>(
  SignatureRequestStatusEnum,
  "SignatureRequestStatus"
);
