/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { Id } from "./Id";
import * as t from "io-ts";

// required attributes
const SignerDetailViewR = t.interface({
  id: Id
});

// optional attributes
const SignerDetailViewO = t.partial({});

export const SignerDetailView = t.exact(
  t.intersection([SignerDetailViewR, SignerDetailViewO], "SignerDetailView")
);

export type SignerDetailView = t.TypeOf<typeof SignerDetailView>;
