/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { ThirdPartyAttachment } from "./ThirdPartyAttachment";
import * as t from "io-ts";

// required attributes
const ThirdPartyMessageR = t.interface({
  attachments: t.readonlyArray(
    ThirdPartyAttachment,
    "array of ThirdPartyAttachment"
  )
});

// optional attributes
const ThirdPartyMessageO = t.partial({});

export const ThirdPartyMessage = t.exact(
  t.intersection([ThirdPartyMessageR, ThirdPartyMessageO], "ThirdPartyMessage")
);

export type ThirdPartyMessage = t.TypeOf<typeof ThirdPartyMessage>;
