/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

export type ThirdPartyMessageAttachmentContent = t.TypeOf<
  typeof ThirdPartyMessageAttachmentContent
>;
export const ThirdPartyMessageAttachmentContent = t.string;
