/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { UTCISODateFromString as UTCISODateFromStringT } from "@pagopa/ts-commons/lib/dates";
import * as t from "io-ts";

/**
 * A date-time field in ISO-8601 format and UTC timezone.
 */

export type Timestamp = t.TypeOf<typeof Timestamp>;
export const Timestamp = UTCISODateFromStringT;
