name: opex-review
description: Generate the dashboard or fail and exit in case of syntax errors

inputs:
  docker_version:
    description: "The version of the docker image to run"
    required: true
    # From https://github.com/pagopa/opex-dashboard/pkgs/container/opex-dashboard
    default: "sha256:04d8ead53c772d23b094c2a395292dc159e6f2905e1b13b5f828f31eac6eb27f"
  template_name:
    description: "The template to use to generate dashbards"
    required: true
    default: "azure-dashboard"
  api_name:
    description: "The name of the API"
    required: true
  environment:
    description: "The environment"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run opex tool
      shell: bash
      run: |
        docker run \
          --workdir /github/workspace --rm \
          -v $(pwd):"/github/workspace" \
          ghcr.io/pagopa/opex-dashboard-azure-action@${{ inputs.docker_version }} \
          ${{ inputs.template_name }} \
          .opex/${{ inputs.api_name }}/env/${{ inputs.environment }}/config.yaml
