/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class CreateSignatureRequestBody {
    /**
    * Entity Id
    */
    'dossierId': string;
    /**
    * Entity Id
    */
    'signerId': string;
    /**
    * A date-time field in ISO-8601 format and UTC timezone.
    */
    'expiresAt'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dossierId",
            "baseName": "dossier_id",
            "type": "string",
            "format": "NonEmptyString"
        },
        {
            "name": "signerId",
            "baseName": "signer_id",
            "type": "string",
            "format": "NonEmptyString"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "string",
            "format": "UTCISODateFromString"
        }    ];

    static getAttributeTypeMap() {
        return CreateSignatureRequestBody.attributeTypeMap;
    }

    public constructor() {
    }
}

