/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class DocumentToBeValidatedAllOf {
    'status': DocumentToBeValidatedAllOfStatusEnum;
    /**
    * A date-time field in ISO-8601 format and UTC timezone.
    */
    'uploadedAt': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "DocumentToBeValidatedAllOfStatusEnum",
            "format": ""
        },
        {
            "name": "uploadedAt",
            "baseName": "uploaded_at",
            "type": "string",
            "format": "UTCISODateFromString"
        }    ];

    static getAttributeTypeMap() {
        return DocumentToBeValidatedAllOf.attributeTypeMap;
    }

    public constructor() {
    }
}


export type DocumentToBeValidatedAllOfStatusEnum = "WAIT_FOR_VALIDATION" ;

