/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SignatureField } from '../models/SignatureField';
import { HttpFile } from '../http/http';

export class DocumentMetadata {
    'title': string;
    'signatureFields': Array<SignatureField>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "signatureFields",
            "baseName": "signature_fields",
            "type": "Array<SignatureField>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DocumentMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}

