/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProblemDetail {
    /**
    * An absolute URI that identifies the problem type. When dereferenced, it SHOULD provide human-readable documentation for the problem type (e.g., using HTML).
    */
    'type'?: string;
    /**
    * A short, summary of the problem type. Written in english and readable for engineers (usually not suited for non technical stakeholders and not localized); example: Service Unavailable
    */
    'title'?: string;
    /**
    * The HTTP status code generated by the origin server for this occurrence of the problem.
    */
    'status'?: number;
    /**
    * A human readable explanation specific to this occurrence of the problem.
    */
    'detail'?: string;
    /**
    * An absolute URI that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
    */
    'instance'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": "string"
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "detail",
            "baseName": "detail",
            "type": "string",
            "format": ""
        },
        {
            "name": "instance",
            "baseName": "instance",
            "type": "string",
            "format": "string"
        }    ];

    static getAttributeTypeMap() {
        return ProblemDetail.attributeTypeMap;
    }

    public constructor() {
    }
}

