/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Clause } from '../models/Clause';
import { SignatureFieldAttrs } from '../models/SignatureFieldAttrs';
import { HttpFile } from '../http/http';

export class SignatureField {
    'attrs': SignatureFieldAttrs;
    'clause': Clause;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "attrs",
            "baseName": "attrs",
            "type": "SignatureFieldAttrs",
            "format": ""
        },
        {
            "name": "clause",
            "baseName": "clause",
            "type": "Clause",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SignatureField.attributeTypeMap;
    }

    public constructor() {
    }
}

