/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SignatureFieldToBeCreatedAttrsCoordinates } from '../models/SignatureFieldToBeCreatedAttrsCoordinates';
import { SignatureFieldToBeCreatedAttrsSize } from '../models/SignatureFieldToBeCreatedAttrsSize';
import { HttpFile } from '../http/http';

export class SignatureFieldToBeCreatedAttrs {
    'coordinates': SignatureFieldToBeCreatedAttrsCoordinates;
    'page': number;
    'size': SignatureFieldToBeCreatedAttrsSize;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "coordinates",
            "baseName": "coordinates",
            "type": "SignatureFieldToBeCreatedAttrsCoordinates",
            "format": ""
        },
        {
            "name": "page",
            "baseName": "page",
            "type": "number",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "SignatureFieldToBeCreatedAttrsSize",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SignatureFieldToBeCreatedAttrs.attributeTypeMap;
    }

    public constructor() {
    }
}

