/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentDetailView } from '../models/DocumentDetailView';
import { NotificationDetailView } from '../models/NotificationDetailView';
import { HttpFile } from '../http/http';

export class SignatureRequestDetailView {
    /**
    * Entity Id
    */
    'id': string;
    'status': string;
    /**
    * Entity Id
    */
    'dossierId': string;
    /**
    * Entity Id
    */
    'signerId': string;
    /**
    * A date-time field in ISO-8601 format and UTC timezone.
    */
    'expiresAt': string;
    'documents': Array<DocumentDetailView>;
    'notification'?: NotificationDetailView;
    /**
    * A date-time field in ISO-8601 format and UTC timezone.
    */
    'createdAt': string;
    /**
    * A date-time field in ISO-8601 format and UTC timezone.
    */
    'updatedAt': string;
    /**
    * A date-time field in ISO-8601 format and UTC timezone.
    */
    'signedAt'?: string;
    /**
    * A date-time field in ISO-8601 format and UTC timezone.
    */
    'rejectedAt'?: string;
    'rejectReason'?: string;
    'qrCodeUrl'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "NonEmptyString"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "dossierId",
            "baseName": "dossier_id",
            "type": "string",
            "format": "NonEmptyString"
        },
        {
            "name": "signerId",
            "baseName": "signer_id",
            "type": "string",
            "format": "NonEmptyString"
        },
        {
            "name": "expiresAt",
            "baseName": "expires_at",
            "type": "string",
            "format": "UTCISODateFromString"
        },
        {
            "name": "documents",
            "baseName": "documents",
            "type": "Array<DocumentDetailView>",
            "format": ""
        },
        {
            "name": "notification",
            "baseName": "notification",
            "type": "NotificationDetailView",
            "format": ""
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": "UTCISODateFromString"
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": "UTCISODateFromString"
        },
        {
            "name": "signedAt",
            "baseName": "signed_at",
            "type": "string",
            "format": "UTCISODateFromString"
        },
        {
            "name": "rejectedAt",
            "baseName": "rejected_at",
            "type": "string",
            "format": "UTCISODateFromString"
        },
        {
            "name": "rejectReason",
            "baseName": "reject_reason",
            "type": "string",
            "format": ""
        },
        {
            "name": "qrCodeUrl",
            "baseName": "qr_code_url",
            "type": "string",
            "format": "string"
        }    ];

    static getAttributeTypeMap() {
        return SignatureRequestDetailView.attributeTypeMap;
    }

    public constructor() {
    }
}

