/* tslint:disable */
/* eslint-disable */
/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentRejectedAllOf
 */
export interface DocumentRejectedAllOf {
    /**
     * 
     * @type {string}
     * @memberof DocumentRejectedAllOf
     */
    status: DocumentRejectedAllOfStatusEnum;
    /**
     * A date-time field in ISO-8601 format and UTC timezone.
     * @type {string}
     * @memberof DocumentRejectedAllOf
     */
    uploadedAt: string;
    /**
     * A date-time field in ISO-8601 format and UTC timezone.
     * @type {string}
     * @memberof DocumentRejectedAllOf
     */
    rejectedAt: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRejectedAllOf
     */
    rejectReason: string;
}


/**
 * @export
 */
export const DocumentRejectedAllOfStatusEnum = {
    Rejected: 'REJECTED'
} as const;
export type DocumentRejectedAllOfStatusEnum = typeof DocumentRejectedAllOfStatusEnum[keyof typeof DocumentRejectedAllOfStatusEnum];


/**
 * Check if a given object implements the DocumentRejectedAllOf interface.
 */
export function instanceOfDocumentRejectedAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "uploadedAt" in value;
    isInstance = isInstance && "rejectedAt" in value;
    isInstance = isInstance && "rejectReason" in value;

    return isInstance;
}

export function DocumentRejectedAllOfFromJSON(json: any): DocumentRejectedAllOf {
    return DocumentRejectedAllOfFromJSONTyped(json, false);
}

export function DocumentRejectedAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentRejectedAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'uploadedAt': json['uploaded_at'],
        'rejectedAt': json['rejected_at'],
        'rejectReason': json['reject_reason'],
    };
}

export function DocumentRejectedAllOfToJSON(value?: DocumentRejectedAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'uploaded_at': value.uploadedAt,
        'rejected_at': value.rejectedAt,
        'reject_reason': value.rejectReason,
    };
}

