/* tslint:disable */
/* eslint-disable */
/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentValidationResult
 */
export interface DocumentValidationResult {
    /**
     * 
     * @type {boolean}
     * @memberof DocumentValidationResult
     */
    isValid: boolean;
    /**
     * 
     * @type {Array<string>}
     * @memberof DocumentValidationResult
     */
    violations?: Array<string>;
}

/**
 * Check if a given object implements the DocumentValidationResult interface.
 */
export function instanceOfDocumentValidationResult(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "isValid" in value;

    return isInstance;
}

export function DocumentValidationResultFromJSON(json: any): DocumentValidationResult {
    return DocumentValidationResultFromJSONTyped(json, false);
}

export function DocumentValidationResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentValidationResult {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isValid': json['is_valid'],
        'violations': !exists(json, 'violations') ? undefined : json['violations'],
    };
}

export function DocumentValidationResultToJSON(value?: DocumentValidationResult | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'is_valid': value.isValid,
        'violations': value.violations,
    };
}

