/* tslint:disable */
/* eslint-disable */
/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DocumentMetadata } from './DocumentMetadata';
import {
    DocumentMetadataFromJSON,
    DocumentMetadataFromJSONTyped,
    DocumentMetadataToJSON,
} from './DocumentMetadata';

/**
 * 
 * @export
 * @interface DocumentToBeUploaded
 */
export interface DocumentToBeUploaded {
    /**
     * Entity Id
     * @type {string}
     * @memberof DocumentToBeUploaded
     */
    id: string;
    /**
     * 
     * @type {DocumentMetadata}
     * @memberof DocumentToBeUploaded
     */
    metadata: DocumentMetadata;
    /**
     * A date-time field in ISO-8601 format and UTC timezone.
     * @type {string}
     * @memberof DocumentToBeUploaded
     */
    createdAt: string;
    /**
     * A date-time field in ISO-8601 format and UTC timezone.
     * @type {string}
     * @memberof DocumentToBeUploaded
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentToBeUploaded
     */
    status: DocumentToBeUploadedStatusEnum;
}


/**
 * @export
 */
export const DocumentToBeUploadedStatusEnum = {
    WaitForUpload: 'WAIT_FOR_UPLOAD'
} as const;
export type DocumentToBeUploadedStatusEnum = typeof DocumentToBeUploadedStatusEnum[keyof typeof DocumentToBeUploadedStatusEnum];


/**
 * Check if a given object implements the DocumentToBeUploaded interface.
 */
export function instanceOfDocumentToBeUploaded(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function DocumentToBeUploadedFromJSON(json: any): DocumentToBeUploaded {
    return DocumentToBeUploadedFromJSONTyped(json, false);
}

export function DocumentToBeUploadedFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentToBeUploaded {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'metadata': DocumentMetadataFromJSON(json['metadata']),
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'status': json['status'],
    };
}

export function DocumentToBeUploadedToJSON(value?: DocumentToBeUploaded | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'metadata': DocumentMetadataToJSON(value.metadata),
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
        'status': value.status,
    };
}

