/* tslint:disable */
/* eslint-disable */
/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { DocumentMetadata } from './DocumentMetadata';
import {
    DocumentMetadataFromJSON,
    DocumentMetadataFromJSONTyped,
    DocumentMetadataToJSON,
} from './DocumentMetadata';

/**
 * 
 * @export
 * @interface DocumentRejected
 */
export interface DocumentRejected {
    /**
     * Entity Id
     * @type {string}
     * @memberof DocumentRejected
     */
    id: string;
    /**
     * 
     * @type {DocumentMetadata}
     * @memberof DocumentRejected
     */
    metadata: DocumentMetadata;
    /**
     * A date-time field in ISO-8601 format and UTC timezone.
     * @type {string}
     * @memberof DocumentRejected
     */
    createdAt: string;
    /**
     * A date-time field in ISO-8601 format and UTC timezone.
     * @type {string}
     * @memberof DocumentRejected
     */
    updatedAt: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRejected
     */
    status: DocumentRejectedStatusEnum;
    /**
     * A date-time field in ISO-8601 format and UTC timezone.
     * @type {string}
     * @memberof DocumentRejected
     */
    uploadedAt: string;
    /**
     * A date-time field in ISO-8601 format and UTC timezone.
     * @type {string}
     * @memberof DocumentRejected
     */
    rejectedAt: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentRejected
     */
    rejectReason: string;
}


/**
 * @export
 */
export const DocumentRejectedStatusEnum = {
    Rejected: 'REJECTED'
} as const;
export type DocumentRejectedStatusEnum = typeof DocumentRejectedStatusEnum[keyof typeof DocumentRejectedStatusEnum];


/**
 * Check if a given object implements the DocumentRejected interface.
 */
export function instanceOfDocumentRejected(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "metadata" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "uploadedAt" in value;
    isInstance = isInstance && "rejectedAt" in value;
    isInstance = isInstance && "rejectReason" in value;

    return isInstance;
}

export function DocumentRejectedFromJSON(json: any): DocumentRejected {
    return DocumentRejectedFromJSONTyped(json, false);
}

export function DocumentRejectedFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentRejected {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'metadata': DocumentMetadataFromJSON(json['metadata']),
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'status': json['status'],
        'uploadedAt': json['uploaded_at'],
        'rejectedAt': json['rejected_at'],
        'rejectReason': json['reject_reason'],
    };
}

export function DocumentRejectedToJSON(value?: DocumentRejected | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'metadata': DocumentMetadataToJSON(value.metadata),
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
        'status': value.status,
        'uploaded_at': value.uploadedAt,
        'rejected_at': value.rejectedAt,
        'reject_reason': value.rejectReason,
    };
}

