/* tslint:disable */
/* eslint-disable */
/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import type { SignatureField } from "./SignatureField";
import {
  SignatureFieldFromJSON,
  SignatureFieldFromJSONTyped,
  SignatureFieldToJSON,
} from "./SignatureField";

/**
 *
 * @export
 * @interface DocumentMetadata
 */
export interface DocumentMetadata {
  /**
   *
   * @type {string}
   * @memberof DocumentMetadata
   */
  title: string;
  /**
   *
   * @type {Array<SignatureField>}
   * @memberof DocumentMetadata
   */
  signatureFields?: Array<SignatureField>;
}

/**
 * Check if a given object implements the DocumentMetadata interface.
 */
export function instanceOfDocumentMetadata(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "title" in value;

  return isInstance;
}

export function DocumentMetadataFromJSON(json: any): DocumentMetadata {
  return DocumentMetadataFromJSONTyped(json, false);
}

export function DocumentMetadataFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): DocumentMetadata {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    title: json["title"],
    signatureFields: !exists(json, "signature_fields")
      ? undefined
      : (json["signature_fields"] as Array<any>).map(SignatureFieldFromJSON),
  };
}

export function DocumentMetadataToJSON(value?: DocumentMetadata | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    title: value.title,
    signature_fields:
      value.signatureFields === undefined
        ? undefined
        : (value.signatureFields as Array<any>).map(SignatureFieldToJSON),
  };
}
