/* tslint:disable */
/* eslint-disable */
/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentReadyAllOf
 */
export interface DocumentReadyAllOf {
    /**
     * 
     * @type {string}
     * @memberof DocumentReadyAllOf
     */
    status: DocumentReadyAllOfStatusEnum;
    /**
     * A date-time field in ISO-8601 format and UTC timezone.
     * @type {string}
     * @memberof DocumentReadyAllOf
     */
    uploadedAt: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentReadyAllOf
     */
    url: string;
}


/**
 * @export
 */
export const DocumentReadyAllOfStatusEnum = {
    Ready: 'READY'
} as const;
export type DocumentReadyAllOfStatusEnum = typeof DocumentReadyAllOfStatusEnum[keyof typeof DocumentReadyAllOfStatusEnum];


/**
 * Check if a given object implements the DocumentReadyAllOf interface.
 */
export function instanceOfDocumentReadyAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "uploadedAt" in value;
    isInstance = isInstance && "url" in value;

    return isInstance;
}

export function DocumentReadyAllOfFromJSON(json: any): DocumentReadyAllOf {
    return DocumentReadyAllOfFromJSONTyped(json, false);
}

export function DocumentReadyAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentReadyAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'uploadedAt': json['uploaded_at'],
        'url': json['url'],
    };
}

export function DocumentReadyAllOfToJSON(value?: DocumentReadyAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'uploaded_at': value.uploadedAt,
        'url': value.url,
    };
}

