/* tslint:disable */
/* eslint-disable */
/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentToBeValidatedAllOf
 */
export interface DocumentToBeValidatedAllOf {
    /**
     * 
     * @type {string}
     * @memberof DocumentToBeValidatedAllOf
     */
    status: DocumentToBeValidatedAllOfStatusEnum;
    /**
     * A date-time field in ISO-8601 format and UTC timezone.
     * @type {string}
     * @memberof DocumentToBeValidatedAllOf
     */
    uploadedAt: string;
}


/**
 * @export
 */
export const DocumentToBeValidatedAllOfStatusEnum = {
    WaitForValidation: 'WAIT_FOR_VALIDATION'
} as const;
export type DocumentToBeValidatedAllOfStatusEnum = typeof DocumentToBeValidatedAllOfStatusEnum[keyof typeof DocumentToBeValidatedAllOfStatusEnum];


/**
 * Check if a given object implements the DocumentToBeValidatedAllOf interface.
 */
export function instanceOfDocumentToBeValidatedAllOf(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "uploadedAt" in value;

    return isInstance;
}

export function DocumentToBeValidatedAllOfFromJSON(json: any): DocumentToBeValidatedAllOf {
    return DocumentToBeValidatedAllOfFromJSONTyped(json, false);
}

export function DocumentToBeValidatedAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentToBeValidatedAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'uploadedAt': json['uploaded_at'],
    };
}

export function DocumentToBeValidatedAllOfToJSON(value?: DocumentToBeValidatedAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'uploaded_at': value.uploadedAt,
    };
}

