/* tslint:disable */
/* eslint-disable */
/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSignerByFiscalCodeBody
 */
export interface GetSignerByFiscalCodeBody {
    /**
     * User's fiscal code.
     * @type {string}
     * @memberof GetSignerByFiscalCodeBody
     */
    fiscalCode: string;
}

/**
 * Check if a given object implements the GetSignerByFiscalCodeBody interface.
 */
export function instanceOfGetSignerByFiscalCodeBody(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "fiscalCode" in value;

    return isInstance;
}

export function GetSignerByFiscalCodeBodyFromJSON(json: any): GetSignerByFiscalCodeBody {
    return GetSignerByFiscalCodeBodyFromJSONTyped(json, false);
}

export function GetSignerByFiscalCodeBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSignerByFiscalCodeBody {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fiscalCode': json['fiscal_code'],
    };
}

export function GetSignerByFiscalCodeBodyToJSON(value?: GetSignerByFiscalCodeBody | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'fiscal_code': value.fiscalCode,
    };
}

