/* tslint:disable */
/* eslint-disable */
/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NotificationDetailView
 */
export interface NotificationDetailView {
    /**
     * 
     * @type {string}
     * @memberof NotificationDetailView
     */
    ioMessageId: string;
}

/**
 * Check if a given object implements the NotificationDetailView interface.
 */
export function instanceOfNotificationDetailView(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "ioMessageId" in value;

    return isInstance;
}

export function NotificationDetailViewFromJSON(json: any): NotificationDetailView {
    return NotificationDetailViewFromJSONTyped(json, false);
}

export function NotificationDetailViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): NotificationDetailView {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ioMessageId': json['io_message_id'],
    };
}

export function NotificationDetailViewToJSON(value?: NotificationDetailView | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'io_message_id': value.ioMessageId,
    };
}

