/* tslint:disable */
/* eslint-disable */
/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignatureRequestListView
 */
export interface SignatureRequestListView {
    /**
     * Entity Id
     * @type {string}
     * @memberof SignatureRequestListView
     */
    id: string;
    /**
     * Entity Id
     * @type {string}
     * @memberof SignatureRequestListView
     */
    signerId: string;
    /**
     * Entity Id
     * @type {string}
     * @memberof SignatureRequestListView
     */
    dossierId: string;
    /**
     * 
     * @type {string}
     * @memberof SignatureRequestListView
     */
    status: string;
    /**
     * A date-time field in ISO-8601 format and UTC timezone.
     * @type {string}
     * @memberof SignatureRequestListView
     */
    createdAt: string;
    /**
     * A date-time field in ISO-8601 format and UTC timezone.
     * @type {string}
     * @memberof SignatureRequestListView
     */
    updatedAt: string;
    /**
     * A date-time field in ISO-8601 format and UTC timezone.
     * @type {string}
     * @memberof SignatureRequestListView
     */
    expiresAt: string;
}

/**
 * Check if a given object implements the SignatureRequestListView interface.
 */
export function instanceOfSignatureRequestListView(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "signerId" in value;
    isInstance = isInstance && "dossierId" in value;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;
    isInstance = isInstance && "expiresAt" in value;

    return isInstance;
}

export function SignatureRequestListViewFromJSON(json: any): SignatureRequestListView {
    return SignatureRequestListViewFromJSONTyped(json, false);
}

export function SignatureRequestListViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignatureRequestListView {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'signerId': json['signer_id'],
        'dossierId': json['dossier_id'],
        'status': json['status'],
        'createdAt': json['created_at'],
        'updatedAt': json['updated_at'],
        'expiresAt': json['expires_at'],
    };
}

export function SignatureRequestListViewToJSON(value?: SignatureRequestListView | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'signer_id': value.signerId,
        'dossier_id': value.dossierId,
        'status': value.status,
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
        'expires_at': value.expiresAt,
    };
}

