/* tslint:disable */
/* eslint-disable */
/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignerDetailView
 */
export interface SignerDetailView {
    /**
     * Entity Id
     * @type {string}
     * @memberof SignerDetailView
     */
    id: string;
}

/**
 * Check if a given object implements the SignerDetailView interface.
 */
export function instanceOfSignerDetailView(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;

    return isInstance;
}

export function SignerDetailViewFromJSON(json: any): SignerDetailView {
    return SignerDetailViewFromJSONTyped(json, false);
}

export function SignerDetailViewFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignerDetailView {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function SignerDetailViewToJSON(value?: SignerDetailView | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

