/* tslint:disable */
/* eslint-disable */
/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    ExistingSignatureFieldAttrs,
    instanceOfExistingSignatureFieldAttrs,
    ExistingSignatureFieldAttrsFromJSON,
    ExistingSignatureFieldAttrsFromJSONTyped,
    ExistingSignatureFieldAttrsToJSON,
} from './ExistingSignatureFieldAttrs';
import {
    SignatureFieldToBeCreatedAttrs,
    instanceOfSignatureFieldToBeCreatedAttrs,
    SignatureFieldToBeCreatedAttrsFromJSON,
    SignatureFieldToBeCreatedAttrsFromJSONTyped,
    SignatureFieldToBeCreatedAttrsToJSON,
} from './SignatureFieldToBeCreatedAttrs';

/**
 * @type SignatureFieldAttrs
 * 
 * @export
 */
export type SignatureFieldAttrs = ExistingSignatureFieldAttrs | SignatureFieldToBeCreatedAttrs;

export function SignatureFieldAttrsFromJSON(json: any): SignatureFieldAttrs {
    return SignatureFieldAttrsFromJSONTyped(json, false);
}

export function SignatureFieldAttrsFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignatureFieldAttrs {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...ExistingSignatureFieldAttrsFromJSONTyped(json, true), ...SignatureFieldToBeCreatedAttrsFromJSONTyped(json, true) };
}

export function SignatureFieldAttrsToJSON(value?: SignatureFieldAttrs | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }

    if (instanceOfExistingSignatureFieldAttrs(value)) {
        return ExistingSignatureFieldAttrsToJSON(value as ExistingSignatureFieldAttrs);
    }
    if (instanceOfSignatureFieldToBeCreatedAttrs(value)) {
        return SignatureFieldToBeCreatedAttrsToJSON(value as SignatureFieldToBeCreatedAttrs);
    }

    return {};
}

