/* tslint:disable */
/* eslint-disable */
/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Clause } from './Clause';
import {
    ClauseFromJSON,
    ClauseFromJSONTyped,
    ClauseToJSON,
} from './Clause';
import type { SignatureFieldAttrs } from './SignatureFieldAttrs';
import {
    SignatureFieldAttrsFromJSON,
    SignatureFieldAttrsFromJSONTyped,
    SignatureFieldAttrsToJSON,
} from './SignatureFieldAttrs';

/**
 * 
 * @export
 * @interface SignatureField
 */
export interface SignatureField {
    /**
     * 
     * @type {SignatureFieldAttrs}
     * @memberof SignatureField
     */
    attrs: SignatureFieldAttrs;
    /**
     * 
     * @type {Clause}
     * @memberof SignatureField
     */
    clause: Clause;
}

/**
 * Check if a given object implements the SignatureField interface.
 */
export function instanceOfSignatureField(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "attrs" in value;
    isInstance = isInstance && "clause" in value;

    return isInstance;
}

export function SignatureFieldFromJSON(json: any): SignatureField {
    return SignatureFieldFromJSONTyped(json, false);
}

export function SignatureFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignatureField {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'attrs': SignatureFieldAttrsFromJSON(json['attrs']),
        'clause': ClauseFromJSON(json['clause']),
    };
}

export function SignatureFieldToJSON(value?: SignatureField | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'attrs': SignatureFieldAttrsToJSON(value.attrs),
        'clause': ClauseToJSON(value.clause),
    };
}

