/* tslint:disable */
/* eslint-disable */
/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SignatureFieldToBeCreatedAttrsSize
 */
export interface SignatureFieldToBeCreatedAttrsSize {
    /**
     * 
     * @type {number}
     * @memberof SignatureFieldToBeCreatedAttrsSize
     */
    w: number;
    /**
     * 
     * @type {number}
     * @memberof SignatureFieldToBeCreatedAttrsSize
     */
    h: number;
}

/**
 * Check if a given object implements the SignatureFieldToBeCreatedAttrsSize interface.
 */
export function instanceOfSignatureFieldToBeCreatedAttrsSize(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "w" in value;
    isInstance = isInstance && "h" in value;

    return isInstance;
}

export function SignatureFieldToBeCreatedAttrsSizeFromJSON(json: any): SignatureFieldToBeCreatedAttrsSize {
    return SignatureFieldToBeCreatedAttrsSizeFromJSONTyped(json, false);
}

export function SignatureFieldToBeCreatedAttrsSizeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignatureFieldToBeCreatedAttrsSize {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'w': json['w'],
        'h': json['h'],
    };
}

export function SignatureFieldToBeCreatedAttrsSizeToJSON(value?: SignatureFieldToBeCreatedAttrsSize | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'w': value.w,
        'h': value.h,
    };
}

