/* tslint:disable */
/* eslint-disable */
/**
 * Firma con IO - Issuer API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SignatureRequestListView } from './SignatureRequestListView';
import {
    SignatureRequestListViewFromJSON,
    SignatureRequestListViewFromJSONTyped,
    SignatureRequestListViewToJSON,
} from './SignatureRequestListView';

/**
 * 
 * @export
 * @interface SignatureRequestList
 */
export interface SignatureRequestList {
    /**
     * 
     * @type {Array<SignatureRequestListView>}
     * @memberof SignatureRequestList
     */
    items: Array<SignatureRequestListView>;
    /**
     * 
     * @type {string}
     * @memberof SignatureRequestList
     */
    continuationToken?: string;
}

/**
 * Check if a given object implements the SignatureRequestList interface.
 */
export function instanceOfSignatureRequestList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "items" in value;

    return isInstance;
}

export function SignatureRequestListFromJSON(json: any): SignatureRequestList {
    return SignatureRequestListFromJSONTyped(json, false);
}

export function SignatureRequestListFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignatureRequestList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(SignatureRequestListViewFromJSON)),
        'continuationToken': !exists(json, 'continuationToken') ? undefined : json['continuationToken'],
    };
}

export function SignatureRequestListToJSON(value?: SignatureRequestList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': ((value.items as Array<any>).map(SignatureRequestListViewToJSON)),
        'continuationToken': value.continuationToken,
    };
}

