/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const TokenResourceR = t.interface({
  token: t.string
});

// optional attributes
const TokenResourceO = t.partial({});

export const TokenResource = t.exact(
  t.intersection([TokenResourceR, TokenResourceO], "TokenResource")
);

export type TokenResource = t.TypeOf<typeof TokenResource>;
