/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";

// required attributes
const ExistingSignatureFieldAttrsR = t.interface({
  unique_name: t.string
});

// optional attributes
const ExistingSignatureFieldAttrsO = t.partial({});

export const ExistingSignatureFieldAttrs = t.exact(
  t.intersection(
    [ExistingSignatureFieldAttrsR, ExistingSignatureFieldAttrsO],
    "ExistingSignatureFieldAttrs"
  )
);

export type ExistingSignatureFieldAttrs = t.TypeOf<
  typeof ExistingSignatureFieldAttrs
>;
