/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { Id } from "./Id";
import * as t from "io-ts";

// required attributes
const NotificationR = t.interface({
  io_message_id: Id
});

// optional attributes
const NotificationO = t.partial({});

export const Notification = t.exact(
  t.intersection([NotificationR, NotificationO], "Notification")
);

export type Notification = t.TypeOf<typeof Notification>;
