/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { FiscalCode } from "./FiscalCode";
import { NonEmptyString } from "@pagopa/ts-commons/lib/strings";

// required attributes
const RequireFiscalCodeOrVatNumber1R = t.interface({
  fiscal_code: FiscalCode
});

// optional attributes
const RequireFiscalCodeOrVatNumber1O = t.partial({});

export const RequireFiscalCodeOrVatNumber1 = t.exact(
  t.intersection(
    [RequireFiscalCodeOrVatNumber1R, RequireFiscalCodeOrVatNumber1O],
    "RequireFiscalCodeOrVatNumber1"
  )
);

export type RequireFiscalCodeOrVatNumber1 = t.TypeOf<
  typeof RequireFiscalCodeOrVatNumber1
>;

// required attributes
const RequireFiscalCodeOrVatNumber2R = t.interface({
  vat_number: NonEmptyString
});

// optional attributes
const RequireFiscalCodeOrVatNumber2O = t.partial({});

export const RequireFiscalCodeOrVatNumber2 = t.exact(
  t.intersection(
    [RequireFiscalCodeOrVatNumber2R, RequireFiscalCodeOrVatNumber2O],
    "RequireFiscalCodeOrVatNumber2"
  )
);

export type RequireFiscalCodeOrVatNumber2 = t.TypeOf<
  typeof RequireFiscalCodeOrVatNumber2
>;

export const RequireFiscalCodeOrVatNumber = t.union(
  [RequireFiscalCodeOrVatNumber1, RequireFiscalCodeOrVatNumber2],
  "RequireFiscalCodeOrVatNumber"
);

export type RequireFiscalCodeOrVatNumber = t.TypeOf<
  typeof RequireFiscalCodeOrVatNumber
>;
