/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { NonNegativeNumber } from "@pagopa/ts-commons/lib/numbers";

// required attributes
const SignatureFieldToBeCreatedAttrsCoordinatesR = t.interface({
  x: t.number,

  y: t.number
});

// optional attributes
const SignatureFieldToBeCreatedAttrsCoordinatesO = t.partial({});

export const SignatureFieldToBeCreatedAttrsCoordinates = t.exact(
  t.intersection(
    [
      SignatureFieldToBeCreatedAttrsCoordinatesR,
      SignatureFieldToBeCreatedAttrsCoordinatesO
    ],
    "SignatureFieldToBeCreatedAttrsCoordinates"
  )
);

export type SignatureFieldToBeCreatedAttrsCoordinates = t.TypeOf<
  typeof SignatureFieldToBeCreatedAttrsCoordinates
>;

// required attributes
const SignatureFieldToBeCreatedAttrsSizeR = t.interface({
  w: NonNegativeNumber,

  h: NonNegativeNumber
});

// optional attributes
const SignatureFieldToBeCreatedAttrsSizeO = t.partial({});

export const SignatureFieldToBeCreatedAttrsSize = t.exact(
  t.intersection(
    [SignatureFieldToBeCreatedAttrsSizeR, SignatureFieldToBeCreatedAttrsSizeO],
    "SignatureFieldToBeCreatedAttrsSize"
  )
);

export type SignatureFieldToBeCreatedAttrsSize = t.TypeOf<
  typeof SignatureFieldToBeCreatedAttrsSize
>;

// required attributes
const SignatureFieldToBeCreatedAttrsR = t.interface({
  coordinates: SignatureFieldToBeCreatedAttrsCoordinates,

  page: NonNegativeNumber,

  size: SignatureFieldToBeCreatedAttrsSize
});

// optional attributes
const SignatureFieldToBeCreatedAttrsO = t.partial({});

export const SignatureFieldToBeCreatedAttrs = t.exact(
  t.intersection(
    [SignatureFieldToBeCreatedAttrsR, SignatureFieldToBeCreatedAttrsO],
    "SignatureFieldToBeCreatedAttrs"
  )
);

export type SignatureFieldToBeCreatedAttrs = t.TypeOf<
  typeof SignatureFieldToBeCreatedAttrs
>;
