/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { SignatureFieldAttrs } from "./SignatureFieldAttrs";
import { Clause } from "./Clause";
import * as t from "io-ts";

// required attributes
const SignatureFieldR = t.interface({
  attrs: SignatureFieldAttrs,

  clause: Clause
});

// optional attributes
const SignatureFieldO = t.partial({});

export const SignatureField = t.exact(
  t.intersection([SignatureFieldR, SignatureFieldO], "SignatureField")
);

export type SignatureField = t.TypeOf<typeof SignatureField>;
