/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { ExistingSignatureFieldAttrs } from "./ExistingSignatureFieldAttrs";
import { SignatureFieldToBeCreatedAttrs } from "./SignatureFieldToBeCreatedAttrs";

export const SignatureFieldAttrs = t.union(
  [ExistingSignatureFieldAttrs, SignatureFieldToBeCreatedAttrs],
  "SignatureFieldAttrs"
);

export type SignatureFieldAttrs = t.TypeOf<typeof SignatureFieldAttrs>;
