/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { PatternString } from "@pagopa/ts-commons/lib/strings";
import * as t from "io-ts";

export type AssertionRefSha512 = t.TypeOf<typeof AssertionRefSha512>;
export const AssertionRefSha512 = PatternString(
  "^(sha512-[A-Za-z0-9-_=]{1,88})$"
);
