/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import * as t from "io-ts";
import { AssertionRefSha256 } from "./AssertionRefSha256";
import { AssertionRefSha384 } from "./AssertionRefSha384";
import { AssertionRefSha512 } from "./AssertionRefSha512";

export const AssertionRef = t.union(
  [AssertionRefSha256, AssertionRefSha384, AssertionRefSha512],
  "AssertionRef"
);

export type AssertionRef = t.TypeOf<typeof AssertionRef>;
