/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { PatternString } from "@pagopa/ts-commons/lib/strings";
import * as t from "io-ts";

/**
 * A lollipop's JWT auth custom header as `Bearer <JWT Token>`
 */

export type LollipopAuthBearer = t.TypeOf<typeof LollipopAuthBearer>;
export const LollipopAuthBearer = PatternString("^Bearer [a-zA-Z0-9-_].+");
