/**
 * Do not edit this file it is auto-generated by io-utils / gen-api-models.
 * See https://github.com/pagopa/io-utils
 */
/* eslint-disable  */

import { OidcSignedJwt } from "./OidcSignedJwt";
import * as t from "io-ts";

// required attributes
const OidcUserInfoR = t.interface({
  id_token: OidcSignedJwt,

  claims_token: OidcSignedJwt
});

// optional attributes
const OidcUserInfoO = t.partial({});

export const OidcUserInfo = t.intersection(
  [OidcUserInfoR, OidcUserInfoO],
  "OidcUserInfo"
);

export type OidcUserInfo = t.TypeOf<typeof OidcUserInfo>;
