oa3_spec: apps/io-func-sign-issuer/openapi.yaml
name: opex_api_issuer
location: West Europe
timespan: 10m
data_source: /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-rg-internal/providers/Microsoft.ApiManagement/service/io-p-apim-api
resource_type: api-management
action_groups:
  - /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-rg-common/providers/microsoft.insights/actionGroups/SlackPagoPA
  - /subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-rg-common/providers/microsoft.insights/actionGroups/EmailPagoPA
overrides:
  hosts:
    - api.io.pagopa.it
  endpoints:
    /dossiers:
      response_time_threshold: 2
    /dossiers/{id}:
      response_time_threshold: 2
    /signers:
      response_time_threshold: 2
    /signature-requests:
      response_time_threshold: 2
    /signature-requests/{id}:
      response_time_threshold: 2
    /signature-requests/{id}/status:
      response_time_threshold: 2
    /signature-requests/{req_id}/documents/{doc_id}/upload_url:
      response_time_threshold: 2
    /signature-requests/{req_id}/notification:
      response_time_threshold: 2
