# This workflow will perform the code review on each code change.

name: "Code Review"

on:
  push:
    branches: ["main"]
    paths:
      - apps/**
      - packages/**
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - apps/**
      - packages/**
  workflow_dispatch: {}

jobs:
  code_review:
    timeout-minutes: 10 # temp fix
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: pagopa/dx/.github/actions/node-setup@7df458f8cbef8c62cf5ebffd0cfe738a98740ece

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: "Generate API models"
        run: pnpm -r run generate:api-models

      - name: "Code review"
        run: pnpm run code-review --skipNxCache
