# This workflow will perform the code review on each code change.
# It uses "actions/cache" and turborepo in order to perform tasks only on changed files.

name: "Code Review"

on:
  push:
    branches: ["main"]
    paths:
      - apps/**
      - packages/**
  pull_request:
    types: [opened, synchronize]
    paths:
      - apps/**
      - packages/**
  workflow_dispatch: {}

jobs:
  code_review:
    timeout-minutes: 10 # temp fix
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Cache turbo build setup
        uses: actions/cache@2f8e54208210a422b2efd51efaa6bd6d7ca8920f # v3
        with:
          path: node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: "Generate API models"
        run: yarn workspaces foreach --all run generate:api-models

      - name: "Code review"
        run: yarn run code-review
