name: Deploy (backoffice-app-itn)

on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy
    uses: pagopa/dx/.github/workflows/web_app_deploy.yaml@cf9cc21cfc649c7ba6a962096c8088cdd695305e
    secrets: inherit
    with:
      workspace_name: io-sign-backoffice-app
      environment: app-prod
      resource_group_name: io-p-itn-sign-backend-rg-01
      web_app_name: io-p-itn-sign-backoffice-app-01
      use_staging_slot: true
