name: Deploy (user-func)

on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy
    uses: pagopa/dx/.github/workflows/web_app_deploy.yaml@main
    secrets: inherit
    with:
      workspace_name: io-func-sign-user
      environment: app-prod
      resource_group_name: io-p-sign-backend-rg
      web_app_name: io-p-sign-user-func
      use_staging_slot: true