name: Deploy (backoffice-app-itn)

on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy
    uses: pagopa/dx/.github/workflows/release-azure-appsvc-v1.yaml@e392d5787298e8ef0da3fd46a07a4fed65ec4423
    secrets: inherit
    with:
      workspace_name: io-sign-backoffice-app
      environment: app-prod
      resource_group_name: io-p-itn-sign-rg-01
      web_app_name: io-p-itn-sign-backoffice-app-01
      disable_auto_staging_deploy: true
    permissions:
      attestations: write
      contents: read
      id-token: write
