name: Deploy

on:
  workflow_call:
    inputs:
      workspace-name:
        required: true
        type: string
      environment:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - run: npx turbo@1.9.3 prune --scope ${{ inputs.workspace-name }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
          cache-dependency-path: "./out/yarn.lock"

      - run: yarn install --immutable
        working-directory: ./out

      - uses: actions/cache@v3
        with:
          path: ./out/node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - run: yarn build
        working-directory: ./out

      - id: make_artifact
        uses: "./.github/workflows/make-artifact"
        with:
          workspace-name: ${{ inputs.workspace-name }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.workspace-name }}
          path: ${{ steps.make_artifact.outputs.artifact-path }}

  deploy:
    if: ${{ !github.event.act }}
    needs: [build]
    runs-on: self-hosted
    environment: ${{ inputs.environment }}

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.workspace-name }}

      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - uses: azure/webapps-deploy@v2
        with:
          resource-group-name: ${{ vars.AZURE_WEB_APP_RESOURCE_GROUP }}
          app-name: ${{ vars.AZURE_WEB_APP_NAME }}
          slot-name: ${{ vars.AZURE_WEB_APP_SLOT }}
          package: artifact.zip

  #swap_slot:
  #  if: ${{ !github.event.act }}
  #  needs: [deploy]
  #  runs-on: self-hosted
  #  environment: ${{ inputs.environment }}

  #  permissions:
  #    id-token: write
  #    contents: read

  #  steps:
  #    - run: curl -f 'https://${{ vars.AZURE_WEB_APP_NAME }}-staging.azurewebsites.net/health'

  #    - uses: azure/login@v1
  #      with:
  #        client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  #    - run: az webapp deployment slot swap -g ${{ vars.AZURE_WEB_APP_RESOURCE_GROUP }} -n ${{ vars.AZURE_WEB_APP_NAME }} --slot staging --target-slot production
