name: Deploy

on:
  workflow_call:
    inputs:
      workspace-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - run: npx turbo@1.9.3 prune --scope ${{ inputs.workspace-name }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
          cache-dependency-path: "./out/yarn.lock"

      - run: yarn install --immutable
        working-directory: ./out

      - uses: actions/cache@v3
        with:
          path: ./out/node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - run: yarn build
        working-directory: ./out

      - id: detect-workspace-type
        run: |
          if [ -e "host.json" ]; then
            echo "workspace-type=function-app" >> "$GITHUB_OUTPUT"
          elif [ -e "next.config.js" ] && grep -q 'output: "standalone"' "next.config.js"; then
            echo "workspace-type=next-standalone" >> "$GITHUB_OUTPUT"
          else
            exit 1
          fi
        working-directory: ./out/apps/${{ inputs.workspace-name }}

      - if: ${{ steps.detect-workspace-type.outputs.workspace-type == 'next-standalone' }}
        id: make-next-standalone-artifact
        run: |
          mv .next/static .next/standalone/apps/${{ inputs.workspace-name }}/.next/
          cd .next/standalone/apps/${{ inputs.workspace-name }} 
          zip -r artifact.zip .
          echo "artifact-path=$(realpath artifact.zip)" >> "$GITHUB_OUTPUT"
        working-directory: ./out/apps/${{ inputs.workspace-name }}

      - if: ${{ steps.detect-workspace-type.outputs.workspace-type == 'function-app' }}
        id: make-function-app-artifact
        run: |
          npm pkg set --json "bundledDependencies"=true
          npm pkg set --json "files"='["**/function.json", "dist", "host.json","extensions.csproj"]'
          npx npm-pack-zip --destination artifact.zip
          echo "artifact-path=$(realpath artifact.zip)" >> "$GITHUB_OUTPUT"
        working-directory: ./out/apps/${{ inputs.workspace-name }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.workspace-name }}
          path: ${{ steps[format('make-{0}-artifact', steps.detect-workspace-type.outputs.workspace-type)].outputs.artifact-path }}
