name: Deploy (user-func)

on:
  workflow_dispatch: {}
  push:
    tags:
      - io-func-sign-user@**

jobs:
  deploy_workspace_to_azure:
    name: Deploy
    uses: pagopa/io-std/.github/workflows/deploy-workspace.yaml@main
    with:
      environment: io-p-sign-user-func
      workspace-name: io-func-sign-user
    secrets: inherit
