name: Deploy (user-func)

on:
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy
    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@main
    secrets: inherit
    with:
      workspace_name: io-func-sign-user
      environment: webapp-prod-cd
      resource_group_name: io-p-sign-backend-rg
      function_app_name: io-p-sign-user-func
      health_check_path: /api/v1/sign/info
      use_staging_slot: true