name: Deploy

on:
  workflow_call:
    inputs:
      workspace-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - run: npx turbo@1.9.3 prune --scope ${{ inputs.workspace-name }}

      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
          cache: "yarn"
          cache-dependency-path: "./out/yarn.lock"

      - run: yarn install --immutable
        working-directory: ./out

      - uses: actions/cache@v3
        with:
          path: ./out/node_modules/.cache/turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - run: yarn build
        working-directory: ./out

      - id: make_artifact
        uses: "./.github/workflows/make-artifact"
        with:
          workspace-name: ${{ inputs.workspace-name }}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.workspace-name }}
          path: ${{ steps.make_artifact.outputs.artifact-path }}
