name: PR - IO Sign ITN TF Apply

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/italynorth/prod/**"
      - "infra/italynorth/_modules/**"
      - ".github/workflows/itn-tf-deploy.yaml"

jobs:
  prod_itn_core_deploy:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@723b8233cd9c48bac7cc9e796471d4e12d4f8e5c # main
    name: Prod - Code Deploy
    secrets: inherit
    with:
      environment: prod
      base_path: infra/italynorth
      override_github_environment: infra-prod
      use_private_agent: true
