# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: "Labeler"

on: [pull_request]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: bcoe/conventional-release-labels@886f696738527c7be444262c327c89436dfb95a8 # pin@v1
        with:
          type_labels: '{ "feat": "feat", "fix": "fix", "breaking": "breaking-change", "chore": "chore", "refactor": "refactor", "docs": "docs", "test": "test" }'
          ignored_types: "[]"
