name: Opex Dashboard api_support review

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'apps/io-func-sign-support/openapi.yaml'
      - '.github/workflows/opex_api_support.yaml'
      - '.opex/api_support/**'

env:
  API_NAME: api_support

permissions:
  id-token: write
  contents: read

jobs:
  opex-review:
    runs-on: ubuntu-latest
    environment: opex-prod-ci
    steps:
      - name: Checkout
        id: checkout
        # from https://github.com/actions/checkout/releases/tag/v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Validate opex dashboard
        uses: ./.github/workflows/opex-review
        with:
          environment: prod
          api_name: ${{ env.API_NAME }}
