name: "Publish to NPM"

on:
  workflow_dispatch:
    inputs:
      package:
        type: choice
        description: NPM package to publish
        options:
          - "@io-sign/io-sign"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
          scope: "@io-sign"
      - run: yarn
      - run: yarn workspace ${{ github.event.inputs.package }} generate:api-models
      - run: yarn workspace ${{ github.event.inputs.package }} build
      - run: "yarn workspace ${{ github.event.inputs.package }} npm publish --access=public"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
