name: PR - IO Sign TF Apply

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "infra/resources/prod/**"
      - ".github/workflows/tf-deploy.yaml"

jobs:
  prod_itn_core_deploy:
    uses: pagopa/dx/.github/workflows/infra_apply.yaml@36ff122137235d814f3dbd20068acfb521d3fd74 # main
    name: Prod - Code Deploy
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
